name:                safe-tensor-sparse-tensor-compat
version:             0.1.0.0
github:              "nilsalex/safe-tensor"
license:             MIT
author:              "Nils Alex"
maintainer:          "nils.alex@fau.de"
copyright:           "2020 Nils Alex"

extra-source-files:
- README.md

description:         Please see the README on GitHub at <https://github.com/nilsalex/safe-tensor/packages/safe-tensor-sparse-tensor-compat#readme>

dependencies:
- base >=4.7 && <5
- safe-tensor >=0.1 && <0.2
- sparse-tensor >=0.3 && <0.4
- singletons >=2.5 && <2.8
- containers >=0.6 && <0.7
- mtl >=2.2 && <2.3

library:
  source-dirs: src
  when:
  - condition: impl(ghc >=8.10)
    default-extensions: StandaloneKindSignatures

