resolver: nightly-2020-07-04

packages:
- .
- ../safe-tensor

extra-deps:
- git: https://github.com/nilsalex/sparse-tensor.git
  commit: 01543a57ac82a921bb497fc8e75c3d6e9a9be19e
  subdirs:
    - package
