name:                safe-tensor
version:             0.1.0.0
github:              "nilsalex/safe-tensor"
license:             MIT
author:              "Nils Alex"
maintainer:          "nils.alex@fau.de"
copyright:           "2020 Nils Alex"

extra-source-files:
- README.md
- ChangeLog.md

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on GitHub at <https://github.com/githubuser/safe-tensor#readme>

dependencies:
- base >=4.7 && <5
- singletons >=2.5 && <2.8
- constraints >=0.12 && <0.13
- mtl >=2.2 && <2.3

library:
  source-dirs: src
  exposed-modules:
    - Math.Tensor
    - Math.Tensor.Safe
  when:
    - condition: impl(ghc >=8.10)
      default-extensions: StandaloneKindSignatures

