name:                safe-tensor
version:             0.2.1.0
github:              "nilsalex/safe-tensor"
license:             MIT
author:              "Nils Alex"
maintainer:          "nils.alex@fau.de"
copyright:           "2020 Nils Alex"

extra-source-files:
- README.md
- CHANGELOG.md

synopsis:            Dependently typed tensor algebra
category:            Math

description:         For an introduction to the library, see "Math.Tensor.Safe".
                     For more information, see the README on GitHub at <https://github.com/nilsalex/safe-tensor#readme>

dependencies:
- base >=4.7 && <5
- deepseq >=1.4 && <1.5
- singletons >=2.5 && <2.8
- constraints >=0.10 && <0.13
- mtl >=2.2 && <2.3
- containers >=0.6 && <0.7
- hmatrix >=0.20 && <0.21

library:
  source-dirs: src
  ghc-options:
    # - -O2

    # - -fspecialise
    # - -fcross-module-specialise
    # - -fspecialise-aggressively
    # - -fexpose-all-unfoldings

  - -Wall
