name:                repl
version:             0.1.0.0
github:              "nilsalex/safe-tensor"
license:             MIT
author:              "Nils Alex"
maintainer:          "nils.alex@fau.de"
copyright:           "2020 Nils Alex"

extra-source-files:
- README.md

description:         Please see the README on GitHub at <https://github.com/nilsalex/safe-tensor#readme>

dependencies:
- base >=4.7 && <5
- safe-tensor >=0.2.1 && <0.3
- safe-tensor-sparse-tensor-compat >=0.1 && <0.2
- mtl >=2.2 && <2.3
- containers
- text
- haskeline

library:
  source-dirs: src
  ghc-options:
  - -Wall

executables:
  repl-exe:
    main:                Main.hs
    source-dirs:         app
    dependencies:
    - repl
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N

    - -Wall
