name:                example
version:             0.1.0.0
github:              "nilsalex/safe-tensor"
license:             MIT
author:              "Nils Alex"
maintainer:          "nils.alex@fau.de"
copyright:           "2020 Nils Alex"

extra-source-files:
- README.md

description:         Please see the README on GitHub at <https://github.com/nilsalex/safe-tensor#readme>

dependencies:
- base >=4.7 && <5
- safe-tensor >=0.1 && <0.2
- safe-tensor-sparse-tensor-compat >=0.1 && <0.2
- mtl >=2.2 && <2.3

library:
  source-dirs: src
  ghc-options:
  - -O2

  - -fspecialise
  - -fcross-module-specialise
  - -fspecialise-aggressively
  - -fexpose-all-unfoldings

  - -Wall

executables:
  run:
    main:                Main.hs
    source-dirs:         app
    dependencies:
    - example
    ghc-options:
    - -fspecialise
    - -fcross-module-specialise
    - -fspecialise-aggressively
    - -fexpose-all-unfoldings

    - -threaded
    - -rtsopts
    - -with-rtsopts=-N

    - -Wall
