resolver: nightly-2021-02-27

packages:
- .
- ../../packages/safe-tensor
- ../../packages/safe-tensor-sparse-tensor-compat

extra-deps:
- git: https://github.com/nilsalex/sparse-tensor.git
  commit: 6e1dbc8194c00e1a4aa29e86e65284740e8ace85
  subdirs:
    - package
